---
title: "Git workflows for R users"
output: html_document
---

# Basic Git Workflows
<br><br>

This does not cover the installation or set-up of Git, nor does it cover advanced workflows with Stash 



# Workflows 1: Initializing your repository set up

## 1.1 Starting a completely new project

* Step 1: Make a new repository on github and grab the link from the `clone with SSH` option.
* Step 2: Make a new project in R studio with Git control and copy the link.
<br><br>



## 1.2 An existing project on your PC that is not yet tracked by Git

* First make a remote repository on Github and grab the link from the `clone with SSH` option.
* Browse through the right folder in the command line, or browse in your normal explorer to the right folder and right click "Git Bash here":

```{}
#Initialize git tracking
$ git init

#Add the remote repository
$ git remote add origin YourGithubLink

#Add and commit the files
$ git add -A
$ git commit m "commit message"

#Make the link between the local and remote repository
$ git push -u origin master

```
<br><br>

## 1.3 An existing project on Github but not yet on your pc

Browse to the right root folder and just type:
```{}
#Making a copy of the repository 
$ git clone TheGithubLink

```
<br><br>



# Workflow 2: Basic commits of your work

```{}
#First check whether you have the latest material
$ git pull

#Optional: check the differences between working directory, staging area and git directory
$ git status

#Optional: what are the changes I made to the code
$ git diff

#Add all the files to the staging area
$ git add -A

#Make a commit on your work
$ git commit -m "enter your commit message"

#Push your latest commit to github
$ git push
```
<br><br>


# Workflow 3: Branches
Bigger changes are best made on a branch first, and only merged onto the master after they are fully working

you can create the remote branch at any time, after checkout or only just before the first push. I find it easiest to make it straight after creation so I don't forget

Adding -u ensures that the local and remote branch are connected.

```{}
#Optional: List all existing branches (local and remote)
$ git branch -a

#Creating a new branch locally
$ git branch YourBranchName

#Creating the new branch remotely
$ git push -u origin YourBranchName

#Swapping to the new branch to work on
$ git checkout YourBranchName
```


(...)
#Work, add, commit and push on the new branch 
(...)

Ready to merge the branch with the master?

```{}
#Changing back to master branch
$ git checkout master

#Make sure your copy of master is up to date
$ git pull origin master

#Merging the branch on the master
$ git merge YourBranchName

#Optional: check the merged branches, YourBranchName should be in the list
$ git branch --merged

#Push the changes of master to the remote repository
$ git push origin master

#Deleting the branch locally
$ git branch -d YourBranchName

#Deleting the branch remotely
$ git push origin --delete YourBranchName

```
<br><br>



# Workflow 4: Ooops... I want to undo

```{}
#Undo the changes made on an R file (not staged yet!) and return the previous version
$ git checkout filename.R

#Undo a commit without losing the actual commit
$ git revert hashcode_to_revertcommit


#Removing files from the staging area to working directory
$ git reset
```
<br><br>


# Workflow 5: Oh no... undo-undo-undo

```{}
Show log
$ git log

Quit the log list when you got what you need



```
<br><br>




## committing on the wrong branch

```
#find the previous hashcode
$ git log 

$ git checkout BranchName

#cherry-pick commit from master to branch
$ git cherry-pick paste_haschode_here

#shows log on branchname with the new commit
$ git log

#deleting the commit on the master branch
$ git checkout master
$ git reset 
```




### git resets

$ git reset --soft paste_haschode_here
  Reset to specified commit, but will keep changes in the staging area
  
$ git reset  paste_haschode_here
  Default setting. Reset to specified commit, changes are in the working directory rather than the staging area

$ git reset --hard paste_haschode_here
  Really don't want the changes made, I want to go back to where we were before. All files will match the state    they were at the previous commit. Clears staging area and working directory on tracked files.

#cleans any untracked files and folders
$ git clean -df



# Appendix


### Browsing and terminology 
cd foldername
cd ..
#shows inside contents 
$ ls

Naming
* Origin: the name of the remote repository
* Master: the default name of the primary branch
* HEAD: 


git log
git reflog: shows commits in order of reference, walk through of exactly what you did


## Git add 
* git add -A    stages all files
* git add .     stages new and modified, without deleted
* git add -u    stages modified and deleted, without new
* git add file.R stages just the 'file.R' file